services:
  db:
    image: postgres
    restart: always
    shm_size: 1gb
    environment:
      POSTGRES_USER: matchserv_user
      POSTGRES_PASSWORD: matchserv_pass
      POSTGRES_DB: matchserv
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_data:
